---
title: "Portland Maine Tide Chart"
output:
  html_document:
    includes:
      in_header: header.html
---

<style>
h1.title{font-size:28px;text-align:center;}
.nav-pills{display: flex;justify-content: center;}
.text{margin:auto;width:90%;}
.btn1{color: #fff; background-color: #337ab7;border-radius: 20px;border:none;padding: 8px 15px;}
</style>


```{r setup, include=FALSE, cache = FALSE}
knitr::opts_chunk$set(echo = FALSE, fig.height = 8)

library(flexdashboard)
# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
library(lubridate)
library(ggplot2)
library(rtide)
library(dplyr)
library(ggpmisc)
library(stringr)
library(httr)
library(glue)
library(jsonlite)
library(tidyr)
library(purrr)
library(htmltools)

#source("R/key.R")
source("R/functions.R")

# saveRDS(weatherData, "wd.rds")
# saveRDS(tideData, "td.rds")
# 
weatherData = readRDS("wd.rds")
tideData = readRDS("td.rds")

tideData = getTideData()
dailyWeather = getWeatherData()

```

```{r panelset, echo=FALSE}
xaringanExtra::use_panelset()
```


## {.tabset .tabset-pills}

### Yesterday


```{r, echo = FALSE}
p1 = tideData %>%
    filter(date == as.Date(Sys.time(), tz = "EST5EDT")-1)

getPlot(p1, tideData)
```

```{r, echo = FALSE}
hr()
```

```{r, echo = FALSE}
date = as.Date(Sys.time(), tz = "EST5EDT")-1
getTextSummary(dailyWeather = dailyWeather, date = date)
```


### Today {.active}

```{r, echo = FALSE}
p1 = tideData %>%
    filter(date == as.Date(Sys.time(), tz = "EST5EDT"))

getPlot(p1, tideData)
```

```{r, echo = FALSE}
hr()
```

```{r, echo = FALSE}
date = as.Date(Sys.time(), tz = "EST5EDT")
getTextSummary(dailyWeather = dailyWeather, date = date)
```

### Tomorrow 

```{r, echo = FALSE}
p2 = tideData %>%
    filter(date == as.Date(Sys.time(), tz = "EST5EDT")+1)

getPlot(p2, tideData)
```

```{r, echo = FALSE}
hr()
```


```{r, echo = FALSE}
date = as.Date(Sys.time(), tz = "EST5EDT")+1
getTextSummary(dailyWeather = dailyWeather, date = date)
```

## {-}

<center>
<button onClick="window.location.reload();" class = "btn1">Refresh</button>
</center>
